male(christopher).
male(andrew).
male(arthur).
male(james).
male(charles).
male(colin).
male(roberto).
male(pierro).
male(emilio).
male(macro).
male(tomaso).
male(alfonso).
female(charlotte).
female(angela).
female(sophia).
female(lucia).
female(gina).
female(francesca).
female(maria).
female(victoria).
female(jannifer).
female(margaret).
female(penelope).
female(christine).
parent(christopher,arthur).
parent(christopher,victoria).
parent(penolope,arthur).
parent(penolope,victoria).
parent(andrew,james).
parent(andrew,jannifer).
parent(christine,jannifer).
parent(christine,james).
parent(victoria,colin).
parent(victoria,charlotte).
parent(james,colin).
parent(james,charlotte).
parent(roberto,emilio).
parent(roberto,lucia).
parent(maria,emilio).
parent(maria,lucia).
parent(pierro,macro).
parent(pierro,angela).
parent(francesca,macro).
parent(francesca,angela).
parent(lucia,alfonso).
parent(macro,alfonso).
parent(lucia,sophia).
parent(macro,sophia).
father(X,Y):-parent(X,Y),male(X).
mother(X,Y):-parent(X,Y),female(X).
brother(X,Y):-parent(Z,X),parent(Z,Y),male(X),X\=Y.
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X),X\=Y.
uncle(X,Y):-brother(X,Z),parent(Z,Y).
aunt(X,Y):-sister(X,Z),parent(Z,Y).
grandfather(X,Y):-father(X,Z),parent(Z,Y).
grandmother(X,Y):-mother(X,Z),parent(Z,Y).
cousin(X,Y):-grandfather(Z,X),grandfather(Z,Y),X\=Y.
cousin(X,Y):-grandmother(Z,X),grandmother(Z,Y),X\=Y.
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(X,Z),ancestor(Z,Y).



